<a href="https://colab.research.google.com/github/Rimuy-Amaya/Python_20250503/blob/main/%E8%87%AA%E5%AD%B8/%E8%80%83%E5%8F%A4%E9%A1%8C20250522.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 陣列
- 什麼是 NumPy？
想像一下，你平常玩的樂高積木，一顆一顆的，你只能一顆一顆拿。
但如果有一天，你拿到了一個神奇的托盤，這個托盤可以把很多樂高積木整齊地、排列整齊地放上去，而且一次就可以拿很多顆，或者把很多顆疊起來，是不是很方便？

- NumPy，就是 Python 程式語言裡的那個「神奇的托盤製造工廠」！
它專門生產一種特殊的「托盤」，這個托盤就叫做「陣列 (array)」。

- 什麼是「陣列 (array)」？
「陣列」就像一個超級整齊的格子本，或者一個很多格子的魔法盒子。

 - **普通變數**： 你以前學的 x = 5，就像一個小盒子，裡面只能放一個數字 5。
 - **列表** (List)： my_list = [1, 2, 3]，就像一個長長的、可以放很多東西的袋子，你可以放樂高、放橡皮擦、放鉛筆，而且它們也不一定要排整齊。

 - **陣列 (Array - NumPy 的 array)**： np.array([6,5,4,3,2,1])，這就像一個非常整齊的、只能放同種類東西的格子本。而且，這個格子本可以是：
一排的格子本 (一維陣列)： 就像一張紙上只有一排格子。
很多排格子的格子本 (二維陣列)： 就像一張紙上有很多排格子，像你畫的數學方格紙。
甚至很多本格子本疊在一起 (三維陣列，或更高維度)： 這就更厲害了！
NumPy 的陣列有什麼特別？

- NumPy 製作的「陣列」這個格子本，有幾個非常棒的優點：

 - 超級整齊： 裡面的東西總是排得整整齊齊的。
 - 速度超快： 因為它排得整齊，電腦處理起來就特別快，比處理列表快很多。
 - 計算方便： 可以一次對很多格子裡的數字做加、減、乘、除，就像魔法一樣！

## NumPy 只用來處理「陣列 (array)」嗎？

是的！NumPy 的核心和主要目的就是處理「陣列 (array)」這種特殊的數據結構。

你可以把 NumPy 想像成一個專門為「陣列」設計的「超級工具箱」。它裡面所有的工具，都是為了讓「陣列」工作得更快、更方便。

雖然它只處理陣列，但這個「陣列」非常非常有用！因為你可以把很多種資料都想像成陣列：

- 圖片： 一張圖片可以用很多數字來表示，這些數字排得整整齊齊就像一個二維陣列。
- 聲音： 一段聲音也是由很多數字組成的波形，可以看作一維陣列。
- 表格數據： 像 Excel 表格一樣的數據，就是一個二維陣列。
- 科學實驗數據： 大量的測量值，通常也是排成陣列的形式。
所以，雖然 NumPy 專注於陣列，但它能處理的資料種類非常廣泛！

## NumPy 的程式碼只有 .array 和 .reshape 嗎？還有什麼？
絕對不是！array 和 reshape 只是 NumPy 工廠裡最基本的兩台機器。NumPy 是一個非常龐大的工廠，裡面有成千上萬種工具和機器！

讓我用「陣列超級工具箱」的比喻，給你介紹一些 NumPy 常用的、超厲害的工具：

### (1) 製作陣列的各種「機器」：
- np.array([1,2,3])： 把列表變成陣列。
- np.zeros((2,3))： 「空白陣列製造機」！它會製造一個全部都是 0 的陣列。
- np.zeros((2,3)) 會做出：
[[0. 0. 0.]
 [0. 0. 0.]]
- np.ones((2,2))： 「全部是 1 的陣列製造機」！
- np.ones((2,2)) 會做出：
[[1. 1.]
 [1. 1.]]
- np.arange(0, 10, 2)： 「數數陣列製造機」！從 0 開始數，每次跳 2，直到 10 (但不包含 10)。
- np.arange(0, 10, 2) 會做出：
[0 2 4 6 8]
- np.random.rand(2,2)： 「隨機數字陣列製造機」！隨機給你一些數字。
- np.random.rand(2,2) 會做出 (數字會不一樣)：
[[0.123 0.456]
 [0.789 0.101]]

### (2) 改變陣列形狀的「變形金剛」：
- .reshape(3,2)： 你已經學過，讓一排的格子變成多排的格子。
- .T 或 .transpose()： 「翻轉機器」！把陣列的橫排變直排，直排變橫排，就像把一張紙從左翻到右。
假設 np_a 是：
[[1 2]
 [3 4]]

np_a.T 會變成：
[[1 3]
 [2 4]]
### (3) 對陣列做數學計算的「超級計算機」：
- .sum(axis=...)： 你已經學過，加總機器，可以指定橫著加還是直著加。
- .mean(axis=...)： 「平均數計算機」！算出平均值。
- .max() / .min()： 「找最大值/最小值機器」！
- np_a + np_b： 「陣列對陣列加法機」！兩個陣列會一個格子對一個格子地相加。
假設 np_a = [1 2], np_b = [3 4]
np_a + np_b 會是 [4 6]
- np_a * 5： 「陣列乘數字機」！陣列裡的每個數字都乘以 5。
假設 np_a = [1 2]
np_a * 5 會是 [5 10]
- np.dot(np_a, np_b) 或 @ 運算符： 「點乘機」或「矩陣乘法機」！這是處理複雜數學（像在工程、科學裡面很常用）的超級工具。
### (4) 篩選陣列裡面的東西的「魔法篩子」：
- np1[np1 > 3]： 「找大於某個數的魔法篩子」！找出陣列中所有大於 3 的數字。
假設 np1 = [6 5 4 3 2 1]
np1[np1 > 3] 會印出 [6 5 4]
- np1[0] 或 np2[0,1]： 「拿出指定格子的東西」！這就像你可以直接從格子本裡面拿出你想要的那個格子裡的數字。

### 這只是 NumPy 龐大功能中的一小部分！它還有很多更複雜的工具，可以用來做：

- 統計分析： 幫你分析數據的各種特徵。
- 線性代數： 處理像方程式組之類的數學問題。
- 傅立葉變換： 分析聲音、圖片等頻率的工具。

所以，NumPy 不僅僅只有 array 和 reshape，它是一個為陣列操作提供極高效率和豐富功能的「超級數學工具箱」！這也是為什麼在科學、工程、數據分析和人工智慧領域，NumPy 幾乎是必不可少的工具。

In [1]:
import numpy as np
np1 = np.array([6,5,4,3,2,1])
np2 = np1.reshape(3,2)
print(np2.sum(axis=1))

ModuleNotFoundError: No module named 'numpy'

In [1]:
import numpy as np

# 第一步：創建一個從 10 到 1 的倒序陣列
data_sequence = np.arange(10, 0, -1) # 注意：第三個參數是步長，負數表示倒序！
print(f"原始陣列: {data_sequence}") # 這是為了方便你追蹤，實際考試不會有

# 第二步：將陣列變形為 2x5 的形狀
matrix_view = data_sequence.reshape(2, 5)
print(f"變形後的矩陣: \n{matrix_view}") # 這是為了方便你追蹤，實際考試不會有

# 第三步：從矩陣中，選擇出所有大於 5 的數字
filtered_elements = matrix_view[matrix_view > 5]
print(f"篩選後的元素: {filtered_elements}") # 這是為了方便你追蹤，實際考試不會有

# 第四步：計算篩選後元素的最大值、最小值和總和
max_val = filtered_elements.max()
min_val = filtered_elements.min()
sum_val = filtered_elements.sum()

# 第五步：將這些計算結果組合成一個新的 NumPy 陣列
final_result = np.array([max_val, min_val, sum_val])

# 最後：印出這個新陣列的第一個元素 (index 0) 和第三個元素 (index 2) 的總和
print(final_result[0] + final_result[2])

ModuleNotFoundError: No module named 'numpy'

# ()與[]的使用時機

**總體原則**：
- [] (方括號)： 主要用於表示 列表 (List)，或者用來進行 索引 (Indexing) 和 切片 (Slicing)。
- () (圓括號)： 主要用於表示 元組 (Tuple)，或者用來表示 函式呼叫 (Function Call)。在 NumPy 的一些特定函數中，它也可能用於表示形狀 (Shape)。

## 什麼時候用 [] (方括號)？

- 創建列表 (List)：
例子： my_array = np.array([6, 5, 4, 3, 2, 1]) (這裡 [6, 5, 4, 3, 2, 1] 是一個列表)
- 索引 (Indexing)：
- 用來從列表、元組、陣列或字符串中取出單個元素。
例子 (列表)： my_list = [10, 20, 30], print(my_list[0]) 會印出 10
例子 (NumPy 陣列)： my_np_array = np.array([10, 20, 30]), print(my_np_array[1]) 會印出 20
- 二維陣列索引： 用來取出特定「行」和「列」的元素。
例子： matrix_view = [[10, 9], [8, 7]], print(matrix_view[0, 1]) 會印出 9 (第一行，第二個元素)
- 切片 (Slicing)：
用來從列表、元組或陣列中取出一部分元素。
例子 (列表)： my_list = [1, 2, 3, 4, 5], print(my_list[1:4]) 會印出 [2, 3, 4]
例子 (NumPy 陣列)： data = np.array([1, 2, 3, 4, 5]), print(data[2:]) 會印出 [3 4 5]
- 條件篩選 (Boolean Indexing)：
NumPy 陣列特有的強大功能，用一個布林 (True/False) 陣列來篩選元素。
例子： matrix_view[matrix_view > 5] (找出 matrix_view 中所有大於 5 的元素)

## 什麼時候用 () (圓括號)？

- 函式呼叫 (Function Call)：
當你想要「啟動」一個函式，讓它執行它的任務時。這是最常見的用途。
例子： print("Hello!")、len("world")
NumPy 中： 當你呼叫 NumPy 的各種函數時。
例子： np.array(...)、np.zeros(...)、np.sum(...)、np.arange(...)

- 創建元組 (Tuple)：
元組是一種不能修改的數據集合。
例子： my_tuple = (1, 2, 3)
- 表示形狀 (Shape) 或多個維度 (Dimensions) (在 NumPy 特定函數中)：
在使用 reshape() 或創建多維陣列時，() 通常用來指定各個維度的大小。
例子： np.zeros((2, 3)) (創建一個 2 行 3 列的零陣列)
例子： np1.reshape(3, 2) (將 np1 變形為 3 行 2 列)
注意： 這裡 (3, 2) 本身是一個元組，用來作為 reshape 函數的一個引數。
算術運算中的優先順序：

- 和數學中一樣，用來改變運算的先後順序。
例子： (2 + 3) * 4 (先算 2+3)

## 常見的混淆點：
np.array([1,2,3]) vs. np.array((1,2,3))：

這兩種寫法在創建一維陣列時都能工作，因為 np.array() 很聰明，它可以把列表或元組都轉換成陣列。
推薦使用 []，因為它更明確地表示你傳入的是一個列表，這在習慣上更常用，也因為列表是可變的，方便你臨時構建數據。
my_array[0, 1] vs. my_array[(0, 1)]：

在 NumPy 中，多維陣列的索引通常用逗號隔開的數字列表來表示 [row_index, col_index]。
你也可以用一個元組來作為索引，例如 my_array[(0, 1)] 也能工作，但直接寫 my_array[0, 1] 更常見、更簡潔。

## 總結：

- [] (方括號)： 創建列表、索引/切片、條件篩選。
- () (圓括號)： 呼叫函式、創建元組、表示形狀/維度。

# 閉包 (Closure) vs. 遞迴 (Recursion)：大比拼

## 1. 閉包 (Closure)：
比喻： 就像一個「會記住秘密的專屬小工廠」。大工廠 (a) 製造出小工廠 (b)，小工廠 (b) 會「記得」大工廠製造它時給它的「秘密」（外層函式的變數）。

- 核心概念： 記憶 (Memory / State) 和 客製化 (Customization)。

- 一個函式（內層函式）「記住」了它被創建時的環境（外層函式的變數），並在之後被呼叫時使用這些記憶。你可以透過外層函式，製造出多個行為類似但「記得」不同秘密的專屬函式。

- 形成方式：
 - 函式巢狀定義 (def 外層函式(): def 內層函式():)
 - 外層函式回傳內層函式 (return 內層函式)
 - 內層函式使用外層函式的變數 (內層函式 裡有 外層函式 的變數)

- 運作方式：

 - 一旦閉包（內層函式）被回傳出來，它就獨立存在了。
 - 當你呼叫這個閉包時，它會利用自己「記住」的秘密和這次呼叫傳入的參數來完成任務。
 - 它不會自己呼叫自己。

- 主要使用時機：

 - 客製化函式： 根據不同的配置或上下文生成具有特定行為的函式。例如：製造加法器(5) 得到一個「加 5 的函式」。
 - 資料隱藏/封裝： 讓一些變數只被閉包內部存取，外部無法直接修改。
 - 函式工廠： 批量生產具有相似但可變行為的函式。
 - 事件處理： 讓事件發生時的回調函式「記得」相關的上下文資訊。

## 2. 遞迴 (Recursion)：

- 比喻： 就像一個「會把任務丟給自己去完成的代辦事項清單」或「俄羅斯娃娃」。要完成一個大任務，函式發現自己做不了，就把任務縮小一點，然後再丟給「另一個自己」去完成，直到任務小到可以直接解決為止。

- 核心概念： 重複執行 (Repetition) 和 分解問題 (Problem Decomposition)。

 - 一個函式在它的定義內部，直接或間接呼叫自己來解決問題。
 - 它將一個大問題分解成一個或多個與原問題相似但規模更小的子問題。

- 形成方式：

 - 遞迴呼叫： 函式內部有呼叫自身的程式碼 (函式名稱(...))。
 - 基本情況 (Base Case)： 必須有一個「終止條件」，當問題小到不能再分解時，直接返回答案，停止遞迴。這是防止「無限迴圈」的關鍵！

- 運作方式：
 - 每次函式呼叫自己時，都會創建一個新的函式執行環境。
 - 這些環境會像疊羅漢一樣堆疊起來，直到遇到基本情況。
 - 然後，結果會一層一層地回傳回來，最終解決最初的大問題。
 - 它會自己呼叫自己。

- 主要使用時機：

 - 數學定義： 例如階乘、費波那契數列等。
 - 樹狀或圖狀結構： 遍歷資料結構（如二元樹的遍歷）。
 - 分治法： 將問題分解為多個獨立的子問題（如快速排序、合併排序）。
 - 某些演算法： 例如深度優先搜尋 (DFS)。
 - 容易混淆嗎？

## 區別的關鍵：

- 遞迴是「自己呼叫自己」來解決問題。
- 閉包是「外層函式回傳內層函式」，內層函式會「記住」外層的變數，但不會自己呼叫自己。

# 閉包的兩個return

## 1. 第一個 return：return v1**v2 (在內層函式 b 裡面)

- 含義： 這個 return 位於內層函式 b 的內部。它的意思是，當你實際使用 (呼叫) b 這個「專屬機器人」的時候，它完成任務後會回傳一個「計算結果」。

- 比喻： 想像你已經有了一個「專屬機器人 B」。當你給它一個任務（例如 a1(3)，把 3 給 v2），它就會按照它「記得」的秘密 (v1) 和你給的任務 (v2)，進行計算 (v1**v2)。這個計算完成後，它就會把計算的結果 (125) 交給你。

- 什麼時候會執行到它？只有當你呼叫被 a 函式回傳出來的那個**「閉包函式」**時（例如 a1(3)），這個 return 才會被執行。

## 2. 第二個 return：return b (在外層函式 a 裡面)

- 含義： 這個 return 位於外層函式 a 的內部。它的意思是，當你**呼叫 a 這個「機器人製造機」**的時候（例如 a1 = a(5)），它完成「製造專屬機器人」的任務後，不會回傳一個數字或最終的計算結果，而是回傳「一個已經設計好的內層函式 b 本身」。

- 比喻： 想像你對「機器人製造機 A」說：「請你幫我製造一個機器人！」這台製造機不會立刻給你掃地的結果，它會把一個新的、已經根據你要求設計好並「記得秘密」的「專屬機器人 B」，交給你。這個「交給你」的動作，就是 return b。

- 什麼時候會執行到它？只有當你呼叫外層函式 a 時（例如 a1 = a(5)），這個 return 才會被執行。它的作用是將內層函式 b 作為一個值，傳遞給外層函式呼叫的結果（例如 a1）。

In [ ]:
def a(v1): # 這是外面的「機器人製造機」
    def b(v2): # 這是「機器人製造機」內部設計出來的「專屬機器人」
        return v1**v2 # <-- 第一個 return
    return b          # <-- 第二個 return

In [ ]:
def make_processor(mode): # 大工廠：設定模式

    def process_number(num): # 小工廠：執行加工
        # 這裡的 'num' 是每次呼叫 'process_number' 時新傳入的！
        if mode == "add":
            return num + 7
        elif mode == "multiply":
            return num * 3
        elif mode == "subtract":
            return num - 4
        else:
            return "UNKNOWN_MODE"

    return process_number

# 創造「加法」小工廠
add_processor = make_processor("add") # 此時 add_processor 記住 mode = "add"

# 第一次呼叫加法小工廠
result_a = add_processor(5) # num = 5，計算 5 + 7 = 12

# 第二次呼叫加法小工廠
result_c = add_processor(12) # num = 12，計算 12 + 7 = 19

In [3]:
公園玩具 = "滑梯" # 全域變數

def 學校():
    學校玩具 = "籃球" # 外層函式（學校）的局部變數

    def 班級():
        班級玩具 = "積木" # 內層函式（班級）的局部變數
        print(f"班級裡有：{班級玩具}")
        print(f"學校裡有：{學校玩具}") # 班級可以看到學校的玩具
        print(f"公園裡有：{公園玩具}") # 班級也可以看到公園的玩具
    return 班級

我們的班級 = 學校()
我們的班級()

班級裡有：積木
學校裡有：籃球
公園裡有：滑梯


In [1]:
def 飲料調配機(基底): # 大工廠：飲料調配機，設定好飲料的「基底」

    def 加入配料(配料): # 小工廠：調配機裡面的「加入配料」功能
        return f"一杯 {基底} 加 {配料}"

    return 加入配料 # 大工廠回傳這個「加入配料」的小工廠

# 步驟一：製造一個「奶茶專用」的調配小工廠
奶茶調配器 = 飲料調配機("奶茶")

# 步驟二：製造一個「綠茶專用」的調配小工廠
綠茶調配器 = 飲料調配機("綠茶")

# 步驟三：使用「奶茶專用」調配器，加入珍珠
結果1 = 奶茶調配器("珍珠")

# 步驟四：使用「綠茶專用」調配器，加入椰果
結果2 = 綠茶調配器("椰果")

# 步驟五：使用「奶茶專用」調配器，加入布丁
結果3 = 奶茶調配器("布丁")


print(結果1)
print(結果2)
print(結果3)

一杯 奶茶 加 珍珠
一杯 綠茶 加 椰果
一杯 奶茶 加 布丁


In [2]:
def make_processor(mode):

    def process_number(num):
        if mode == "add":
            return num + 7
        elif mode == "multiply":
            return num * 3
        elif mode == "subtract":
            return num - 4
        else:
            return "UNKNOWN_MODE"

    return process_number

# Step 1
add_processor = make_processor("add")

# Step 2
multiply_processor = make_processor("multiply")

# Step 3
result_a = add_processor(5)

# Step 4
result_b = multiply_processor(8)

# Step 5
result_c = add_processor(12)

# Step 6
subtract_processor = make_processor("subtract")

# Step 7
result_d = subtract_processor(25)

# Step 8
result_e = multiply_processor(10) # One more challenge!

print(result_a)
print(result_b)
print(result_c)
print(result_d)
print(result_e)

12
24
19
21
30


In [4]:
def process_data(data): # data 接收 my_list 的引用
    data[0] = data[0] * 2 # my_list[0] 從 5 變成 10 (列表是可變的，函式內修改會影響外部)
    return data[0] + data[1] # 返回 10 (現在的 data[0]) + 10 (data[1]) = 20

my_list = [5, 10]
result = process_data(my_list) # result = 20
print(my_list[0]) # 輸出 my_list[0] 的當前值，是 10
print(result)     # 輸出 result 的值，是 20

10
20


In [5]:
def find_sum_recursive(n):
    if n == 1: # 基本情況：n 等於 1 時返回 1
        return 1
    else: # 遞迴情況：n 大於 1
        return n + find_sum_recursive(n - 1) # 呼叫自己，n 減 1

print(find_sum_recursive(4))

10
