https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [14]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3,4))
np.random.random(size=(3,4))




array([[0.02253091, 0.69879478, 0.25588904, 0.05683432],
       [0.32895185, 0.4716059 , 0.57317439, 0.13637032],
       [0.29990964, 0.20492377, 0.71732661, 0.68625451]])

In [18]:
from numpy.random import normal 

normal_value = normal(size=(3, 4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [13]:
normal_value * 10

array([[ 15.16818776, -23.79348059,   0.32382795,  -1.11847176],
       [ 11.54300005,   1.24291547,  -0.30976902,   1.86735558],
       [ -2.76205729,   1.9730439 ,   2.64312667,   2.35892328]])

In [ ]:
normal_value.sum()
normal_value.sum(axis=0) #每一欄加總，共產生四個數字
normal_value.sum(axis=1) #每一列加總，共產生三個數字

array([-0.94199366,  1.43435021,  0.42130366])